### PR TITLE
A simple ping pong game.

### PR DESCRIPTION
**Pull request by Majd-Yahia**
Made for colonistio test.

What I have done:
- Players are controlled by speed attributes.
- Player one and Player two are bound to keyboard inputs w/s and arrow up/down respectively.
- Ball bounce from rackets and walls.
- Score/Win functionality.
- Reset and pause function.
- Players' boundaries.
- Text as a score in canvas.
- Canvas change width/height with browser on refresh.
- Ball changes speed when it bounces from a racket.

#Media
ping_pong

### CODE REVIEW

**Comment by Majd-Yahia** [comment]
@demiculus

**Comment by demiculus** [comment]
Hey @Majd-Yahia 

Nice work, can you do some edits?
Branch off of this branch and continue on the new branch. Then create a new PR merging that new branch to this one and tag me for review.

At the new branch, I want to see a couple of things

1. Clean code: Your code works but it is not clean. Google clean code best practices & principles and apply some of them. In your PR description, include which ones you applied and any detail you feel would add value.
2. Modularity: Increase modularity, feel free to google best practices here as well and apply a few of them.
3. Fun mechanic: The game is a bit boring. Add any mechanic that you think would make the game more fun.
4. Learn gitignore and remove the nodemodules, in another branch, not the review branch. It makes it hellish to review code.

Let me know if there are any questions.

**Comment by Majd-Yahia** [comment]
Greetings Demi,

I have a few questions:
- regarding clean code I have been applying best practices, and from what i
saw the only thing was off was my overuse of comments, do you have any
notes about the functions as they are following the single responsibility
principle?

Kind regards,
Majd K. Yahia.

**Comment by demiculus** [comment]
There are more principles not used, I'll let you figure it out.

**Pull request closed without merging**
