### PR TITLE
Increase code readability + new feature

### PR DESCRIPTION
**Pull request by Trololocos**
For this PR I have tried to make the commits shorter and more understandable. 
I've also made the code clearer, by applying these principles: 

- I've removed "magic numbers"
- I've commented the more potentially confusing stuff
- I've capitalized the constants
- I've removed most of the code repetition and placed it into more modular nested functions

About the modularity, that has been my priority while implementing dunking. Every component is completely replaceable and mostly independent of each other.

https://user-images.githubusercontent.com/47633543/143276873-030a163a-c728-46fd-b62f-0c8badaaa815.mp4
#22 @demiculus

### CODE REVIEW

**Comment by demiculus** [comment]
Alright can you select a time slot here: https://calendly.com/colonist-demi

**Comment by Trololocos** [comment]
Done, november 3rd. How well did I do in the assignment? Good enough I'm
wondering

**Comment by demiculus** [comment]
Its okay, can be cleaned up more

**Comment by goktugyil** [comment]
@demiculus ?

**Pull request closed without merging**
